package com.example.ui

object Localization {
    enum class Language {
        RU, EN
    }

    private val ruStrings = mapOf(
        "calendar" to "Календарь",
        "transactions" to "Транзакции",
        "analytics" to "Аналитика",
        "settings" to "Настройки",
        "go_to_current" to "Перейти на текущий период",
        "add_transaction" to "Добавить транзакцию",
        "edit_transaction" to "Редактировать транзакцию",
        "delete" to "Удалить",
        "save" to "Сохранить",
        "cancel" to "Отмена",
        "amount" to "Сумма",
        "account" to "Счет",
        "category" to "Категория",
        "date" to "Дата",
        "description" to "Описание (необязательно)",
        "type" to "Тип",
        "type_income" to "Доход",
        "type_expense" to "Расход",
        "type_transfer" to "Перевод",
        "recurrence" to "Повторение",
        "rec_none" to "Без повторения",
        "rec_daily" to "Ежедневно",
        "rec_weekly" to "Еженедельно",
        "rec_monthly" to "Ежемесячно",
        "rec_yearly" to "Ежегодно",
        "target_account" to "На счет",
        "transfer_rate" to "Курс перевода (NBRB)",
        "loading_rate" to "Загрузка курса НБРБ...",
        "rate_fetched" to "Курс НБРБ получен",
        "search_placeholder" to "Поиск по описанию...",
        "filters" to "Фильтры",
        "all_accounts" to "Все счета",
        "all_categories" to "Все категории",
        "analytics_period" to "Период аналитики",
        "period_day" to "День",
        "period_month" to "Месяц",
        "period_year" to "Год",
        "period_all" to "Весь период",
        "total_income" to "Общий доход",
        "total_expense" to "Общий расход",
        "net_balance" to "Чистый остаток",
        "settings_theme" to "Выбор темы оформления",
        "theme_light" to "Светлая",
        "theme_dark" to "Тёмная",
        "theme_system" to "Системная",
        "settings_lang" to "Выбор языка",
        "settings_accounts" to "Настройка счетов",
        "settings_categories" to "Настройка категорий",
        "account_active" to "Активен (участвует в балансе)",
        "account_inactive" to "Неактивен (исключен из баланса)",
        "add_account" to "Добавить счет",
        "edit_account" to "Редактировать счет",
        "account_name" to "Название счета",
        "initial_balance" to "Начальный баланс",
        "currency" to "Валюта",
        "add_category" to "Добавить категорию",
        "edit_category" to "Редактировать категорию",
        "category_name" to "Название категории",
        "category_type" to "Тип категории",
        "empty_transactions" to "Транзакций не найдено",
        "planned" to "Запланировано",
        "conducted" to "Проведено",
        "remaining_on_accounts" to "Остатки по счетам отдельно:",
        "balance_on_day" to "Балансы на этот день",
        "no_expenses_data" to "Нет данных по расходам за этот период",
        "no_incomes_data" to "Нет данных по доходам за этот период",
        "transfers" to "Переводы",
        "chart_title" to "Структура расходов по категориям"
    )

    private val enStrings = mapOf(
        "calendar" to "Calendar",
        "transactions" to "Transactions",
        "analytics" to "Analytics",
        "settings" to "Settings",
        "go_to_current" to "Go to Current Period",
        "add_transaction" to "Add Transaction",
        "edit_transaction" to "Edit Transaction",
        "delete" to "Delete",
        "save" to "Save",
        "cancel" to "Cancel",
        "amount" to "Amount",
        "account" to "Account",
        "category" to "Category",
        "date" to "Date",
        "description" to "Description (optional)",
        "type" to "Type",
        "type_income" to "Income",
        "type_expense" to "Expense",
        "type_transfer" to "Transfer",
        "recurrence" to "Recurrence",
        "rec_none" to "No recurrence",
        "rec_daily" to "Daily",
        "rec_weekly" to "Weekly",
        "rec_monthly" to "Monthly",
        "rec_yearly" to "Yearly",
        "target_account" to "To Account",
        "transfer_rate" to "Transfer Rate (NBRB)",
        "loading_rate" to "Loading rate from NBRB...",
        "rate_fetched" to "NBRB rate loaded",
        "search_placeholder" to "Search description...",
        "filters" to "Filters",
        "all_accounts" to "All Accounts",
        "all_categories" to "All Categories",
        "analytics_period" to "Analytics Period",
        "period_day" to "Day",
        "period_month" to "Month",
        "period_year" to "Year",
        "period_all" to "All Time",
        "total_income" to "Total Income",
        "total_expense" to "Total Expense",
        "net_balance" to "Net Balance",
        "settings_theme" to "Theme Choice",
        "theme_light" to "Light",
        "theme_dark" to "Dark",
        "theme_system" to "System",
        "settings_lang" to "Language Selection",
        "settings_accounts" to "Accounts Management",
        "settings_categories" to "Categories Management",
        "account_active" to "Active (participates in balance)",
        "account_inactive" to "Inactive (excluded from balance)",
        "add_account" to "Add Account",
        "edit_account" to "Edit Account",
        "account_name" to "Account Name",
        "initial_balance" to "Initial Balance",
        "currency" to "Currency",
        "add_category" to "Add Category",
        "edit_category" to "Edit Category",
        "category_name" to "Category Name",
        "category_type" to "Category Type",
        "empty_transactions" to "No transactions found",
        "planned" to "Planned",
        "conducted" to "Conducted",
        "remaining_on_accounts" to "Account balances separately:",
        "balance_on_day" to "Balances on this day",
        "no_expenses_data" to "No expense data for this period",
        "no_incomes_data" to "No income data for this period",
        "transfers" to "Transfers",
        "chart_title" to "Expense Structure by Categories"
    )

    fun get(key: String, language: Language): String {
        return if (language == Language.RU) {
            ruStrings[key] ?: key
        } else {
            enStrings[key] ?: key
        }
    }
}
